import os.path

from constants import INI_ENDS, INI_COMMENTS, SETTINGS_FILE

SETTINGS_DICT = {
    'comment': "// do not edit this file by hand. Use the 'edit settings' option in the application",
    'installation_path': '',
    'BfME2_folder_name': '',
    'RotWK_folder_name': '',
    'game_to_launch': '',
    'editor_to_launch': '',
    'backup_folder': '',
    'modules_library': '',
    'mods_folder_exceptions': [{'folder_exception': ''}],
    'mods_templates': [{'mods_template': ''}],
    'LotM_log_folder': ''
}

GAME_PATH = ''
WORLDBUILDER_PATH = ''
LOG_PATH = ''
MODULES_LIBRARY = ''
BACKUP_FOLDER = ''
EXCEPTION_FOLDERS = []
MODULE_TEMPLATE = ''


def check_settings(mode='lines'):
    """
    Checks the parameters of the SETTINGS_FILE against any deviations from the hardcoded form of the settings.ini
    :return: a list of lines being the split SETTINGS_FILE if it is correct or being valueless if incorrect
    """
    settings_dict = {}
    structure_keys = []
    structure_containers = []
    for structure_key in SETTINGS_DICT:
        if SETTINGS_DICT[structure_key] == '':
            structure_keys.append(structure_key)
        if type(SETTINGS_DICT[structure_key]) is list:
            structure_containers.append(structure_key)
            for container_key in SETTINGS_DICT[structure_key][0]:
                structure_keys.append(container_key)
    container_open = False
    container_name = ''
    try:
        with open(SETTINGS_FILE) as settings_file:
            settings_lines = settings_file.readlines()
        structure_keys_copy = structure_keys.copy()
        for line in settings_lines:
            if ' = ' in line.strip():
                key, value = line.strip().split(' = ')
                if key not in structure_keys:
                    print(f'unrecognized key: {key}')
                    raise FileNotFoundError
                else:
                    try:
                        structure_keys_copy.remove(key)
                    except ValueError:
                        pass
                    if container_open:
                        settings_dict[container_name].append(value)
                    else:
                        settings_dict[key] = value
            elif line.strip() in INI_ENDS:
                container_open = False
            elif line.strip()[0] in INI_COMMENTS:
                settings_dict['comment'] = line.rstrip()
            elif line.strip() != 'Settings' and line.strip() in structure_containers:
                container_name = line.strip()
                container_open = True
                settings_dict[container_name] = []
            else:
                pass
        for missing_key in structure_keys_copy:
            print(f'missing key: {missing_key}')
    except FileNotFoundError:
        mode = 'dict'
        settings_dict = SETTINGS_DICT
    if mode == 'lines':
        return settings_lines
    else:
        return settings_dict


# print(check_settings())


def read_settings():
    """
    :return: a dictionary of settings read from the SETTING_FILE
    """
    settings = check_settings(mode='dict')
    return settings


def load_settings_into_constants():
    """ composes the variables used by the programs functions out of the read settings.

    The sensitivity of the hardcoded values is most probably the biggest weakness of the program."""
    global GAME_PATH, WORLDBUILDER_PATH, MODULES_LIBRARY, BACKUP_FOLDER  # MODS_FOLDER, VERSION_LIBRARY
    global EXCEPTION_FOLDERS, MODULE_TEMPLATE, LOG_PATH
    settings = read_settings()
    try:
        GAME_PATH = '/'.join((settings['installation_path'], settings['RotWK_folder_name'], settings['game_to_launch']))
        WORLDBUILDER_PATH = '/'.join((settings['installation_path'], settings['editor_to_launch']))
        # MODS_FOLDER = '/'.join((settings['installation_path'], settings['mods_folder']))
        # VERSION_LIBRARY = '/'.join((settings['installation_path'], settings['version_library']))
        MODULES_LIBRARY = '/'.join((settings['installation_path'], settings['modules_library']))
        BACKUP_FOLDER = '/'.join((settings['installation_path'], settings['backup_folder']))
        EXCEPTION_FOLDERS.clear()
        for folder in settings['mods_folder_exceptions']:
            EXCEPTION_FOLDERS.append(folder)
        for folder in settings['mods_templates']:
            EXCEPTION_FOLDERS.append(folder)
        MODULE_TEMPLATE = '/'.join((MODULES_LIBRARY, settings['mods_templates'][0]))
        LOG_PATH = settings['LotM_log_folder']
    except KeyError:
        print('load_settings KeyError')
        return
    return GAME_PATH, WORLDBUILDER_PATH, MODULES_LIBRARY, \
        BACKUP_FOLDER, EXCEPTION_FOLDERS, MODULE_TEMPLATE, LOG_PATH  # MODS_FOLDER, VERSION_LIBRARY


load_settings_into_constants()


def save_settings(dictionary_settings=None, **keyword_settings):
    """
    Saves the values provided (inserted in the application) to the SETTING_FILE.
    Then it checks if the new settings are valid. If not, retrieves the previous settings.
    :param dictionary_settings: settings organized in a dictionary
    :param keyword_settings: settings as key-word arguments-values pairs
    :return: string sentence about success or failure to find the paths provided
    """
    if not keyword_settings and dictionary_settings is not None:
        keyword_settings = dictionary_settings
    settings = read_settings()
    settings_lines = check_settings()
    with open(SETTINGS_FILE.replace('.ini', '_backup.ini'), 'w') as settings_file_copy:
        settings_file_copy.write(''.join(settings_lines))
    settings_new_content = ''
    container_name = ''
    container_open = False
    container_counter = 0
    for line in settings_lines:
        if ' = ' in line:
            key, value = line.strip().split(' = ')
            if key in keyword_settings and not container_open:
                settings_new_content += line.replace(value, keyword_settings[key])
            elif container_open and container_name in keyword_settings:
                if container_counter + 1 == len(settings[container_name]):
                    for setting_value in keyword_settings[container_name]:
                        settings_new_content += line.replace(value, setting_value)
                container_counter += 1
            else:
                settings_new_content += line
        elif line.strip() in INI_ENDS:
            settings_new_content += line
            container_open = False
        elif line.strip() != 'Settings':
            settings_new_content += line
            container_open = True
            container_name = line.strip()
            container_counter = 0
        else:
            settings_new_content += line
    with open(SETTINGS_FILE, 'w') as settings_file:
        settings_file.write(settings_new_content)
    save_file = True
    check_paths = load_settings_into_constants()
    for path in check_paths:
        try:
            if not os.path.exists(path) and save_file:
                if not os.path.exists(os.path.abspath(path)):
                    if not os.path.exists(path.split()[0]):
                        save_file = False
        except TypeError:
            for folder in path:
                if not os.path.exists(f'{MODULES_LIBRARY}/{folder}'):
                    save_file = False
                    break
    if not save_file:
        with open(SETTINGS_FILE.replace('.ini', '_backup.ini'), 'r') as settings_file_copy:
            settings_content = settings_file_copy.read()
            with open(SETTINGS_FILE, 'w') as settings_file:
                settings_file.write(settings_content)
        return 'settings_editor.save_settings error: the provided value seems to be incorrect'
    else:
        return 'settings saved and checked.'

# print(save_settings(mods_templates=['__empty base']))  # , 'yes', 'AotR8-INI_backup'
